apiVersion : apps/v1
kind: Deployment
metadata:
  name: "learningk8-1064"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "learningk8-1064"
  template:
    metadata:
      labels:
        app: "learningk8-1064"
    spec:
      containers:
        - name: "learningk8-1064"
          image: "learningk8.azurecr.io/learningk8"
          ports:
          - containerPort: 5000