apiVersion: v1
kind: Service
metadata:
    name: "learningk8-1064"
    labels:
        app: "learningk8-1064"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "learningk8-1064"